Entity Framework/VNCExplore_EF6_JulieLerman/M4 M5 After/MvcSalesApp.Web/Controllers/CustomersController.cs
using DisconnectedGenericRepository;
using Maintenance.Domain;
using System.Net;
using System.Web.Mvc;

namespace MvcSalesApp.Controllers
{
  public class CustomersController : Controller
  {
    private GenericRepository<Customer> _repo;

    public CustomersController(GenericRepository<Customer> repo) {
      _repo = repo;
    }
   
    public ActionResult Index() {
      return View(_repo.All());
    }

    public ActionResult Details(int? id) {
      if (id == null) {
        return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
      }
      Customer customer = _repo.FindByKey(id.Value);
      if (customer == null) {
        return HttpNotFound();
      }
      return View(customer);
    }

    public ActionResult Create() {
      return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create([Bind(Include = "CustomerId,FirstName,LastName,DateOfBirth")] Customer customer) {
      if (ModelState.IsValid) {
        _repo.Insert(customer);
        return RedirectToAction("Index");
      }
      return View(customer);
    }

    public ActionResult Edit(int? id) {
      if (id == null) {
        return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
      }
      Customer customer = _repo.FindByKey(id.Value);
      if (customer == null) {
        return HttpNotFound();
      }
      return View(customer);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "CustomerId,FirstName,LastName,DateOfBirth")] Customer customer) {
      if (ModelState.IsValid) {
        _repo.Update(customer);
        return RedirectToAction("Index");
      }
      return View(customer);
    }

    public ActionResult Delete(int? id) {
      if (id == null) {
        return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
      }
      Customer customer = _repo.FindByKey(id.Value);
      if (customer == null) {
        return HttpNotFound();
      }
      return View(customer);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id) {
      _repo.Delete(id);

      return RedirectToAction("Index");
    }
  }
}

Entity Framework/VNCExplore_EF6_JulieLerman/M4 M5 After/MvcSalesApp.Web/Controllers/CustomersWithOrdersController.cs
using System.Net;
using System.Web.Mvc;
using Maintenance.Data;

namespace MvcSalesApp.Controllers
{
  public class CustomersWithOrdersController : Controller
  {
      private CustomerWithOrdersData _repo;
    public CustomersWithOrdersController(CustomerWithOrdersData repo) {
      _repo = repo;
    }

    public ActionResult Index() {
      return View(_repo.GetAllCustomers());
    }

      public ActionResult Details(int? id) {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      var customer = _repo.FindCustomer(id);
      if (customer == null) {
        return HttpNotFound();
      }
      return View(customer);
    }
  }
}

Entity Framework/VNCExplore_EF6_JulieLerman/M4 M5 After/MvcSalesApp.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcSalesApp.Controllers
{
  public class HomeController : Controller
  {
    public ActionResult Index() {
      return View();
    }

    public ActionResult About() {
      ViewBag.Message = "Your application description page.";

      return View();
    }

    public ActionResult Contact() {
      ViewBag.Message = "Your contact page.";

      return View();
    }
  }
}

Entity Framework/VNCExplore_EF6_JulieLerman/M4 M5 After/MvcSalesApp.Web/Controllers/ProductsController.cs
using DisconnectedGenericRepository;
using System.Net;
using System.Web.Mvc;
using Maintenance.Domain;

namespace MvcSalesApp.Controllers
{
  public class ProductsController : Controller
  {
    private GenericRepository<Product> _repo;

    public ProductsController(GenericRepository<Product> repo) {
      _repo = repo;
    }

    // GET: Products
    public ActionResult Index() {
      return View(_repo.All());
    }

    // GET: Products/Details/5
    public ActionResult Details(int? id) {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Product product = _repo.FindByKey(id.Value);
      if (product == null) {
        return HttpNotFound();
      }
      return View(product);
    }

    // GET: Products/Create
    public ActionResult Create() {
      return View();
    }

    // POST: Products/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create([Bind(Include = "ProductId,Description,Name,ProductionStart")] Product product) {
      if (ModelState.IsValid) {
        _repo.Insert(product);
        return RedirectToAction("Index");
      }

      return View(product);
    }

    // GET: Products/Edit/5
    public ActionResult Edit(int? id) {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Product product = _repo.FindByKey(id.Value);
      if (product == null) {
        return HttpNotFound();
      }
      return View(product);
    }

    // POST: Products/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    //public ActionResult Edit([Bind(Include = "ProductId,Description,Name,ProductionStart")] Product product) {
       public ActionResult Edit(Product product) {

      if (ModelState.IsValid) {
        _repo.Update(product);
        return RedirectToAction("Index");
      }
      return View(product);
    }

    // GET: Products/Delete/5
    public ActionResult Delete(int? id) {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Product product = _repo.FindByKey(id.Value);
      if (product == null) {
        return HttpNotFound();
      }
      return View(product);
    }

    // POST: Products/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id) {
      _repo.Delete(id);
      return RedirectToAction("Index");
    }
  }
}

Entity Framework/VNCExplore_EF6_JulieLerman/M4 M5 After/MvcSalesApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               @Html.ActionLink("Administration", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                     <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                    <li>@Html.ActionLink("Customers With Orders", "Index", "CustomersWithOrders")</li>
                    <li>@Html.ActionLink("Products", "Index", "Products")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>