ASP.NET/ASP.Net MVC/MvcControllers2/Controllers/Hello2Controller.cs
using MvcControllers2.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace MvcControllers2.Controllers
{
    [Log]
    public class Hello2Controller : Controller
    {
        ILogger _logger = null;

        public Hello2Controller(ILogger logger)
        {
            _logger = logger;
        }

        public ActionResult SayHello(int id)
        {
            return View("Hello");
            //return View(id);
        }

        public ContentResult SayHello2(int id)
        {
            var routeData = this.RouteData;
            return Content("SayHello2(int id) from my new Controller that derives from Controller" + id.ToString());
        }

        // id can come from form, querystring, MapRoute default

        public string SayHello3(int id)
        {
            var routeData = this.RouteData;
            return "SayHello3(int id) from my new Controller that derives from Controller" + id.ToString();
        }

        public string SayHello4(int? id)
        {
            var routeData = this.RouteData;
            // Need to check if id is null
            return "SayHello4(int? id) from my new Controller that derives from Controller" + id.ToString();
        }

        public string SayHello5()
        {
            var routeData = this.RouteData;
            return "SayHello5() from my new Controller that derives from Controller";
        }

        // Abstract base class provides this now

        //public void Execute(RequestContext requestContext)
        //{
        //    requestContext.HttpContext.Response.Write("Hello from my Controller that derives from Controller");
        //    _logger.Log("Log Message");
        //}
    }
}

ASP.NET/ASP.Net MVC/MvcControllers2/Controllers/HelloController.cs
using MvcControllers2.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace MvcControllers2.Controllers
{
    public class HelloController : IController
    {
        ILogger _logger = null;

        public HelloController(ILogger logger)
        {
            _logger = logger;
        }

        public void Execute(RequestContext requestContext)
        {
            requestContext.HttpContext.Response.Write("Hello from my Controller that derives from IController");
            _logger.Log("Log Message");
        }
    }
}

ASP.NET/ASP.Net MVC/MvcControllers2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcControllers2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ASP.NET/ASP.Net MVC/MvcControllers2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        Route Links (NB. Need to add additional parameters to vary Action)
        <ul>
            <li>@Html.RouteLink("SayHello", "SayHello")</li>
            <li>@Html.RouteLink("SayHello2", "SayHello2")</li>
        </ul>
        Action Links
        <ul>
            <li>@Html.ActionLink("Hello", "SayHello", "Hello")</li>
            <li>@Html.ActionLink("Hello2-SayHello(int id)", "SayHello", "Hello2")</li>
            <li>@Html.ActionLink("Hello2-SayHello2(int id)", "SayHello2", "Hello2")</li>
            <li>@Html.ActionLink("Hello2-SayHello3(int id)", "SayHello3", "Hello2")</li>
            <li>@Html.ActionLink("Hello2-SayHello4(int? id)", "SayHello4", "Hello2")</li>
            <li>@Html.ActionLink("Hello2-SayHello5()", "SayHello5", "Hello2")</li>
        </ul>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>